name: cd-workload2
permissions:
  contents: read
  id-token: write
on:
  push:
    branches:
      - main
    paths:
      - 'score/workload2/**'
      - '.github/workflows/cd-workload2.yaml'
env:
  SCORE_HUMANITEC_VERSION: latest
  APP_NAME: sh-demo2
  WORKLOAD_NAME: workload2
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: score-spec/setup-score@v2
        with:
          file: score-humanitec
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_HUMANITEC_VERSION }}
      - name: Deploy using Score
        run: |
          score-humanitec delta \
            --env development \
            --app ${{ env.APP_NAME }} \
            --org="${{ secrets.HUMANITEC_ORG_ID }}" \
            --token "${{ secrets.HUMANITEC_TOKEN }}" \
            -f score/${{ env.WORKLOAD_NAME }}/score.yaml \
            --extensions score/${{ env.WORKLOAD_NAME }}/humanitec.score.yaml
            --deploy
